### PR TITLE
refactor(items): make passing an owner optional in item methods

### PR DESCRIPTION
**Pull request by jgravois**
one option to address @noahmulfinger's excellent feedback in #73

AFFECTS PACKAGES:
@esri/arcgis-rest-items

### CODE REVIEW

**Comment by patrickarlt** [comment]
@jgravois I actually think this sets us up with a bad pattern for routes which will require additional params for the URL but no auth: because then you have to do this:

```ts
getItemFromFolder("itemId", null, null, "folder");
```

since you will have to pass `null` or `{}` for `requestOptions` and maybe params just to get to pass in a folder.

**Comment by jgravois** [comment]
> Seems like `IUserSessionRequestOptions` will be needed in other packages too, right?

i assume it will. my first re-useable instinct would be to move it into `auth` because `common-types` doesn't currently have any external dependencies of its own.

@patrickarlt as far as i know, all the methods with `owner/owner?` definitely  _require_ the request to be authenticated.

**Comment by patrickarlt** [comment]
if we are going to require each thing in the URL segment things could get out of hand really fast and we should just consider switching to passing in a single object:

```ts
createItem({
  item: IItem,
  owner: "patrickarlt",
  params: {
    /* any other params */
  },
  authentication: mySession
})
```

and switch `request` to 

```ts
request({
  url: "http://",
  params: {
    /* whatever */
  }
  authentication: /* whatever */,
  httpMethod: "POST"
})
```

**Comment by patrickarlt** [comment]
@jgravois for example [reassignItem](https://resources.arcgis.com/en/help/arcgis-rest-api/#/Reassign_Item/02r300000097000000/) needs

* `tagetUsername` (required)
* `targetFoldername` (optional)
* `username` (required, part of URL)
* `itemId` (required, part of URL)
* `authentication` (current user may or may not be owner)

I really think we might be better off switching to objects for all of this stuff...

**Comment by jgravois** [comment]
@patrickarlt makes some good points. closing in favor of #78

**Pull request closed without merging**
