### PR TITLE
Example using VueJS

### PR DESCRIPTION
**Pull request by itrew**
Wanted to get my feet wet with this lib and thought it would be helpful to contribute in the process. This is a VueJS app that uses the authentication and request packages. 

Initial template created with [webpack-simple](https://github.com/vuejs-templates/webpack-simple) then added on the vue-router plugin to handle the authentication callbacks.

image

### CODE REVIEW

**Comment by jgravois** [comment]
rock and roll 🎼! it looks like this even resolves #100.

**Comment by itrew** [comment]
Aside from #11, #100 was in my mind when I was creating this. This type of implementation would require some form of routing framework to work, though. 

I'm not entirely sure how to pass a session through a redirect like you mentioned. Perhaps a localStorage implementation? I can mess around with that a bit and see what I find.

**Comment by patrickarlt** [comment]
@itrew do you want to update this with the localstorage solution from https://github.com/Esri/arcgis-rest-js/pull/140 and then I can review it?

**Comment by itrew** [comment]
@patrickarlt Thanks for the feedback, everything makes sense 👍 I'll spend some time in the next couple of days updating #140 with both your's and @jgravois 's input on this.

**Comment by jgravois** [comment]
i agree. thanks for both your contributions and for commenting your code so thoroughly!

**Pull request merged**
