### PR TITLE
fix(arcgis-rest-portal): query terms containing colons need to be wra…

### PR DESCRIPTION
**Pull request by andrewctate**
…pped in quotes to be valid

AFFECTS PACKAGES:
@esri/arcgis-rest-portal

### CODE REVIEW

**Review by tomwayson — COMMENTED** [review]
Thanks @andrewctate 

This stands to reason, but:
1. Looks like no additional test case was needed for coverage, but would you mind adding one to help ensure we don't regress on this in the future
2. @gavinr, @patrickarlt I think we're in a pickle here b/c master has unreleased breaking changes in #904

> After merging this PR: We bump a new major version because our underlying dependencies have new major versions and release. The new release script builds a TypeDoc site and JSON and packages it into the release.

I think to be safe we should revert #904 on master, then merge this.

**Comment by andrewctate** [comment]
@tomwayson thanks. The test case is [here](https://github.com/Esri/arcgis-rest-js/pull/913/files#diff-704937f1df8c53f5d05cef4037d337a9979a3055bb868d2f7b0361c0147501feR42).

**Review by patrickarlt — APPROVED** [review]
LGTM thanks @andrewctate. 

@tomwayson if we want to cut a new release with this in it we can revert https://github.com/Esri/arcgis-rest-js/pull/904/files?file-filters%5B%5D=.json and put it on the 4.0 branch.

**Comment by tomwayson** [comment]
Please wait for #915 before merging this.

**Pull request merged**
