### PR TITLE
fix: geocoder demo on windows #1140

### LINKED ISSUE #1140: Issue running demos on Windows (path/rootDir issue)
### Describe the bug

While trying to run `npm start` **on Windows** in the demo folders, which runs `node ../../scripts/run-demo-server.js` it throws an error in the following line:
https://github.com/Esri/arcgis-rest-js/blob/main/scripts/get-package-json.js#L19

The problem is that the build path in `rootDir` has a semicolon (something like `/D:/..`), and it is causing an exception in Linux based shells like Gitbash.

### Reproduction

You will probably need a Windows machine a follow any of the instructions (e.g. [job demo instructions](https://github.com/Esri/arcgis-rest-js/tree/0e410dc16e0dd2961affb09ff7efbfb9b6c4999a/demos/job))

### Logs

```shell
Sorry, I don't have them.
```

### System Info

```shell
Windows 11.
It was this repo at this point, so ArcGIS REST JS Version: 4.1.4
```

### Additional Information

Sorry, I can not provide more context. It was an easy fix, we just removed the semicolon locally, but I don't have time to submit a PR right now, but I wanted to at least issue this.

### PR DESCRIPTION
**Pull request by BrunoCaimar**
+ fix #1140
+ fix the readme.md instructions and uri redirect.

### CODE REVIEW

**Comment by gavinr-maps** [comment]
@BrunoCaimar thanks for the PR! I will test this shortly and reply with any feedback.

**Review by gavinr-maps — APPROVED** [review]
This works for me on Windows! Looks good from that perspective.

I'd like for someone on a Mac to also test to make sure it still works there.

**Comment by bruno-bizpoke** [comment]
I`ve tested it on a Mac and it works fine. I can provide some screenshots if needed.

**Comment by BrunoCaimar** [comment]
I`ve tested it on a Mac and it works fine. I can provide some screenshots if needed.

**Comment by hhkaos** [comment]
mMmMm I just tested and got this error:
Screenshot 2024-10-16 at 11 49 20

Am I doing something wrong?

I'm on a MacOS Sonoma 14.6.1

**Review by patrickarlt — APPROVED** [review]
This LGTM! I was able to run the Vite demo locally on my Mac

**Pull request merged**
