### PR TITLE
Replace isomorphic-fetch with cross-fetch in node.js guide

### PR DESCRIPTION
**Pull request by pr3tori4n**
**Justification:**
cross-fetch has more up to date dependencies. isomorphic-fetch seems to be unmaintained right now.
https://github.com/lquixada/cross-fetch/blob/master/package.json#L49
https://github.com/matthew-andrews/isomorphic-fetch/blob/master/package.json#L21

**Callouts**
There's several other places in the repo, both in guides and in code that are using isomorphic-fetch. I recommend you update those as well. This is a small start.
Related PR where I'm using cross-fetch succesffuly: https://devtopia.esri.com/WebGIS/arcgis-js-api/pull/20702

### CODE REVIEW

**Comment by jgravois** [comment]
thx for this @pr3tori4n!

i'm going to tack on a couple more commits to make sure we're pointing folks toward `cross-fetch` consistently and see what all we'll need to do to tackle #411 at the same time.

**Comment by jgravois** [comment]
Given that neither pollute the global, i _think_ it makes more sense for `node-fetch` to be our general purpose recommendation than `cross-fetch`.

i just pushed up another commit which:

* shows a code snippet that uses `setDefaultRequestOptions` to take advantage of the ponyfill 🎠.
```js
const fetch = require("node-fetch");
const { request, setDefaultRequestOptions } = require("@esri/arcgis-rest-request");

// use node-fetch for each request instead of relying on a global
setDefaultRequestOptions({ fetch })
```
* updates the Node.js demos to use `"node-fetch"`
* updates the test suite to use `"node-fetch"`
* mentions `"cross-fetch"` in the context of Universal/Isomorphic apps

this addresses @dmfenton's concerns in #411

**Comment by patrickarlt** [comment]
From an ease of use perspective I REALLY prefer just using global fetch even in node.

`cross-fetch` allow you to pull in `node-fetch`:

```js
import fetch from 'cross-fetch'; // this is really just node-fetch

request(someUrl, {fetch}).then(r => {
  console.log(r)
});
```

or as a global:

```js
import 'cross-fetch/polyfill';

request(someUrl).then(r => {
  console.log(r)
});
```

 I think we can promote both approaches in the guide here.

**Comment by jgravois** [comment]
> I think we can promote both approaches in the guide here.

thats fine with me.

something in cross-fetch's Response implementation must be _slightly_ different than what fetch-mock returns because several tests with [`rawResponse`](https://esri.github.io/arcgis-rest-js/api/request/IRequestOptions/#rawResponse) started failing when i swapped in the new dependency. 

```js
expect(response instanceof Response).toBe(true);
```
nothing blocking though, i just replaced them with something more verbose (and arguably a more useful)

```js
expect(response.status).toBe(200);
expect(response.ok).toBe(true);
expect(response.body.Readable).not.toBe(null);
response.json().then((raw: any) => {
  expect(raw).toEqual(cannedResponse);
  done();
});
```

**Comment by jgravois** [comment]
i'd rebase and fix the conflict, but i don't have push access to the repo anymore.

💋

**Pull request merged**
