### PR TITLE
fix: catch err internally when getItemData doesnt find any

### PR DESCRIPTION
**Pull request by jgravois**
AFFECTS PACKAGES:
@esri/arcgis-rest-items

ISSUES CLOSED: #504

### CODE REVIEW

**Comment by patrickarlt** [comment]
@jgravois I'm assigning myself as a reviewer on this one. I actually write some code that watches for this error so I want to see how it behaves.

**Comment by patrickarlt** [comment]
@jgravois ok here is the code I wrote in node:

```js
  try {
    config = await getItemData(options.itemId, {
      authentication: session
    });
  } catch (e) {
    if (e.message === "500: Item does not have a file.") {
      config = {};
    } else if (e.type === "invalid-json") {
      config = {};
    } else {
      log.error(logSymbols.error, "error getting config:", e.message);
      log.trace(e.stack);
      process.exit(1);
    }
  }
```

@jgravois this is actually a breaking change because I want to set `config` to {} if there is an error. The problem here is what should we assume the value should be when there is no data or invalid data? You have it defined as `null` which is technically valid JSON. So  if my item has a data value is actually `null` that is indistinguishable from it not having a value at all which semantically might be more like `undefined` which isn't a valid JSON value. Furthermore this will still throw a syntax error on invalid JSON.

I also complicated things by checking `e.type === "invalid-json"` which isn't actually standard code it is something the `isomorphic-fetch` adds so I'm not really doing it right either.

I'm kind of on the fence as to what I would like to do so I'm going to call in @dbouwman and @tomwayson on this one.

1. Keep your code as it return `null` even though `null` could actually be the value of the data
2. Return `undefined` since nothing was defined in the JSON
3. Don't merge this and keep throwing a syntax error and write some doc for this edge case so people don't run into this.
4. Define a new error type for invalid/no JSON and throw that instead so we can better document this.

**Comment by tomwayson** [comment]
I'm in favor of 

> 3. Return undefined since nothing was defined in the JSON

I was already leaning that way yesterday as @jgravois and I were discussing this.

**Comment by jgravois** [comment]
> I'm in favor of `undefined` since nothing was defined in the JSON

i'm just a caveman geographer, but i assumed the goal was to:

1. avoid forcing the caller to `catch` this error themselves
2. provide an opportunity to check that the response actually contains something

```js
getItemData("fe8")
  .then(response => {
    if (response) {
      // do something with actual JSON
    } 
  })
```
`undefined` and `null` are indistinguishable in that respect.

> return `null` even though `null` could actually be the value of the data

its just trivia, but when @ssylvia and i discussed this in https://github.com/Esri/arcgis-rest-js/issues/495#issuecomment-477306765 we came to the conclusion that there is no way to nullify the `/data` for an item after something has been injected. even if this _were_ possible, i can't think of a scenario where the caller would benefit from us not conflating the two.

i'm just playing devil's advocate though. i don't have a horse in the race, so i've pushed a commit to just `return` and check for `undefined` in the unit test.

caveman lawyer

**Comment by patrickarlt** [comment]
@jgravois I'm fine with `undefined` as the return value here. But 2 things:

1. This technically might be a REALLY minor breaking change.
2. @jgravois will you update the docs on `getItemData()` to reflect that this will be `undefined` is the item has no data.

**Comment by tomwayson** [comment]
To clarify - I was wishy-washy between `null` and `undefined` yesterday, but _leaning towards_ `undefined`. I see pros and cons of each.

The original ask from @qlqllu was for `null`.

**Comment by jgravois** [comment]
> will you update the docs on getItemData()

done.

> This technically might be a REALLY minor breaking change.

you both know i've been itching for an excuse to rip off the band-aid, clean up all the loose ends in #137 and tag `v2.0.0` anyway. if you want to give me the green light to go through and tackle all the rest, just say the word.

@patrickarlt had expressed some interest in taking a crack at #339 and #384 to make sure no _other_ breaking changes would be necessary too though. is this a good time for that?

**Comment by patrickarlt** [comment]
> @patrickarlt had expressed some interest in taking a crack at #339 and #384 to make sure no other breaking changes would be necessary too though. is this a good time for that?

@jgravois I might try to prototype them this week if I have a chance.

**Comment by tomwayson** [comment]
I want to keep that bandaid on forever.

To me this is not a breaking change. I would not say it was intentional for this library to `throw` when there was no data in an item. I think it would be a mistake to have this be the straw that breaks John's beard.

**Comment by jgravois** [comment]
> To me this is not a breaking change.

fwiw, i agree with @tomwayson. i was only capitulating for the sake of 'ulterior motives'.

**Comment by patrickarlt** [comment]
Ok lets merge this and :shipit:

**Pull request merged**
