### PR TITLE
Added new item relationship types

### PR DESCRIPTION
**Pull request by MikeTschudi**
Added new types listed in https://developers.arcgis.com/rest/users-groups-and-items/relationship-types.htm

Updated tslib to 1.10.0 (current) in order to get `npm install` to get past `src/utils/with-options.ts(46,21): error TS2343: This syntax requires an imported helper named '__spreadArrays' which does not exist in 'tslib'. Consider upgrading your version of 'tslib'.` error.

### CODE REVIEW

**Comment by tomwayson** [comment]
Thx @MikeTschudi

What context are you running `npm install` in when you see that message? The root of this monorepo? Your own app/library?

**Comment by MikeTschudi** [comment]
@tomwayson, root

**Comment by tomwayson** [comment]
I'm wary of bumping tslib (and in fact have been wary about even including it as a dependency in the first place since I'm uncertain of how much redundant code it's injecting into the built code). Can you PR _just_ the interface change and I'll merge/release that?

**Comment by MikeTschudi** [comment]
Sounds good to me

**Pull request closed without merging**
