### PR TITLE
Switch out tslint for eslint

### PR DESCRIPTION
**Pull request by COV-GIS**
As suggested by https://github.com/Esri/arcgis-rest-js/issues/844.

@tomwayson, @patrickarlt and/or @gavinr you may want to pull this down and see what you think of how updated prettier transforms many of the src and test files. I didn't realize the how the styling differed between packages, e.g. trailing commas.

I didn't commit the prettied files, but lints and builds without errors.

### CODE REVIEW

**Comment by gavinr** [comment]
Thanks so much for this! I am testing it out - had a few questions:

1. When I make a code change that should cause a linting error (I think), and then running `npm run lint`, I'm expecting an error but not seeing one:
    image

2. I think there are a variety of `tslint:disable...` tags sprinkled throughout the codebase - would we need to change those?

**Comment by gavinr** [comment]
Thanks. It seems to be working now. 

I made a few more changes to make it all work properly:

1. Even though it says to use the string `prettier` [here](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/README.md#usage-with-prettier), based on [this](https://github.com/prettier/eslint-plugin-prettier#recommended-configuration) it's now better to have `"plugin:prettier/recommended"` in the `extends`, and then `prettier` is not necessary in the `plugins. (https://github.com/Esri/arcgis-rest-js/pull/848/commits/2f9d3e4b4fe14f67267a4be482240db24017b400#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L239-L243)

2. I [removed the prettier settings](https://github.com/Esri/arcgis-rest-js/pull/848/commits/2f9d3e4b4fe14f67267a4be482240db24017b400#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L246-L250) because those were the defaults. I will follow-up with the wider code changes that need to be made to conform to these linting rules.
3. Updated the `tslint:` inline comments to their eslint equivalents: https://github.com/Esri/arcgis-rest-js/pull/848/commits/6bca3c01350aefe711860361e216803a53175f5b

I think things are setup pretty well now. As you mentioned, now we'll want to actually make the code changes necessary to conform to these updated eslint/prettier rules. We'll hold off on merging until that's ready on this branch.

## VS Code Notes

To get VS Code to automatically format on save I had to:

1. Disable/uninstall the tslint VS Code plugin
    image

2. Make sure the eslint plugin is installed
    image
3. Set these VS Code settings:
    ```json
    "eslint.format.enable": true,
    "eslint.lintTask.enable": true,
    "[typescript]": {
        "editor.defaultFormatter": "dbaeumer.vscode-eslint",
        "editor.codeActionsOnSave": {
            "source.fixAll.eslint": true
        }
    },
    ```
(more info in the [eslint plugin doc](https://github.com/Microsoft/vscode-eslint))

**Comment by COV-GIS** [comment]
Thanks for tying all together @gavinr.

If there is anything else you wish to task me with concerning this matter just let me know.

**Comment by dbouwman** [comment]
Closing. We switched in #863 which seemed more "surgical". Thanks @COV-GIS & sorry it took us a while to resolve this!

**Pull request closed without merging**
