### PR TITLE
fix(arcgis-rest-request): node ReadStream encoding bug at 3.x

### PR DESCRIPTION
**Pull request by haoliangyu**
This PR addresses the issue https://github.com/Esri/arcgis-rest-js/issues/1033 at rest-js v3. The bug is related to the [form-data](https://github.com/form-data/form-data) library in the node environment. It requires to use an unofficial option to specify the stream length so that the streaming request can end properly (see https://github.com/Esri/arcgis-rest-js/issues/1033#issuecomment-1292016958).

I add a `dataSize` option to the `addItemData()` function so that the user can give a number for the stream data length.

PS: I suspect other functions accepting node ReadStream can have the same issue, but I don't have the availability to verify and fix each API.

PS2: I assume that no more than one stream is used in one API call.

PS3: I have to update the npm version to v7 in CI so that `npm install` won't throw an error.

### CODE REVIEW

**Comment by haoliangyu** [comment]
The CI failed at the Chrome test stage because that required 100% test coverage for the code. But this change is for node environment. Is there a way to bypass the test coverage check for a certain block of code?

**Review by tomwayson — APPROVED** [review]
Nice work @haoliangyu 

I _think_ when this is merged it will trigger a 3.x patch release, but I'm not certain. Let's wait until @dbouwman confirms before merging.

**Comment by dbouwman** [comment]
For rest-js v3, we did not have semantic-release, so you actually want to PR this to `master` and then we manually run the release like we did in the olden times. 

[This PR](https://github.com/Esri/arcgis-rest-js/pull/1024) is the last time we did a 3.x release. 

I can run the scripts if you want. Just lmk via teams once this is merged.

**Comment by tomwayson** [comment]
Thanks @dbouwman, yeah, I just noticed that we don't have  [a .releaserc.json](https://github.com/Esri/hub-components/blob/f46db66efbd29edeee6cfff771b405a4341d1be0/.releaserc.json) file that I believe would be required to run the release on [maintenance branches](https://semantic-release.gitbook.io/semantic-release/usage/workflow-configuration#maintenance-branches).

I've updated the base, and will merge and run the scripts.

**Comment by haoliangyu** [comment]
@tomwayson Do you have any availability to release this at v3.5.1?

**Comment by tomwayson** [comment]
@haoliangyu this has been published as v.3.5.1

**Pull request merged**
