### PR TITLE
docs(bug): ensure sticky links are flagged as active in production

### LINKED ISSUE #284: Documentation pages navigation: highlight currently selected page
I'll admit this is a subjective request, but I personally find it easier when the page I'm on highlights itself in the navigation. It helps me get my bearings if maybe I arrived on this page from a search engine or outside link. So I would propose changing this:
image

to something like this:
image
(notice the background highlight on the selected page in the nav)

Just throwing it out there to see what you all think! Thanks!

### PR DESCRIPTION
**Pull request by jgravois**
a less insane solution than #334 (to resolve #284)

### CODE REVIEW

**Comment by jgravois** [comment]
related: https://github.com/patrickarlt/acetate/pull/74

**Comment by jgravois** [comment]
@noahmulfinger if you can give me a sanity check on this whenever you can spare the time, i'd be _much_ obliged.

**Comment by noahmulfinger** [comment]
@jgravois For some reason the index.js file was not being processed correctly with the right base path. I pushed up a change that creates the index.js manually. 

Also, though unrelated to this PR, I'm seeing a lot of typescript errors when running `npm run docs:serve`.

**Comment by jgravois** [comment]
very cool @noahmulfinger. thank you!

> I'm seeing a lot of typescript errors when running npm run docs:serve.

for sure. i've created #347 to track that.

**Pull request merged**
