### PR TITLE
FeatureService: adds methods and types to fetch Feature Service defin…

### PR DESCRIPTION
**Pull request by tomrussell**
…itions

AFFECTS PACKAGES:
@esri/arcgis-rest-feature-layer
@esri/arcgis-rest-service-admin
@esri/arcgis-rest-types

ISSUES CLOSED: #606

### CODE REVIEW

**Comment by tomwayson** [comment]
thank you @tomrussell, this was released in 2.3.0

**Comment by sandromartis** [comment]
Is it possible that `getService` is not being exported in the `index` file?
I'm not able to import `getService` from `@esri/arcgis-rest-feature-layer`.

I can make a PR to add it.

**Comment by tomwayson** [comment]
What version are you using?

**Comment by sandromartis** [comment]
Version: 2.5.0

I don't see `getService` being exported in `packages/arcgis-rest-feature-layer/src/index.ts` when I check the master branch.

`getService` should be exported in there or am I mistaken?

**Comment by jgravois** [comment]
> `getService` should be exported in `packages/arcgis-rest-feature-layer/src/index.ts`

it definitely should! a pull request with the fix would be welcome.

**Pull request merged**
