### PR TITLE
Add the missing "s" in IStatisticDefinition

### LINKED ISSUE #692: [arcgis-rest-types] IStatisticDefinition.statisticParameter not matching JSAPI statisticParameters
The interface `IStatisticDefinition` has a `statisticParameter` property that doesn't match with the JSAPI (and REST API) `statisticParameters`.

The "s" might have been lost during [this discussion](https://devtopia.esri.com/WebGIS/arcgis-js-api/issues/24952#issuecomment-2036517).

The consequence is that a conversion from `IStatisticDefinition` to `StatisticDefinition` does not translate the `statisticParameter(s)` property:
```ts
const stat: IStatisticDefinition = {
  // ...
  statisticParameter: { ... };
};

const convertedStat = StatisticDefinition.fromJSON(stat); // does not contain a value for `statisticParameters`
```

Could a fix been brought to make that conversion possible ? Thanks !

### PR DESCRIPTION
**Pull request by maneetgoyal**
- Fixes #692

### CODE REVIEW

**Comment by maneetgoyal** [comment]
@subgan82 @tomwayson Can you please review it? An `s` was missing in the property name.
cc @pemberdom

**Comment by tomwayson** [comment]
@maneetgoyal this was released in [2.12.1](https://github.com/Esri/arcgis-rest-js/releases/tag/v2.12.1)

**Comment by subgan82** [comment]
Thanks @tomwayson

**Comment by pemberdom** [comment]
Thanks for the fix!

**Pull request merged**
